---
title: "Day 4: working with friction data"
author: "YOUR NAME HERE"
date: 2024-08-20
format: 
  html:
    embed-resources: true
execute:
  warning: !expr NA
  message: !expr NA
editor: source
---

```{r setup}
library(tidyverse)
library(here)
library(janitor)
library(readxl)
```

# Objectives 

By the end of today, you should be able to...

* Access data from an Excel workbook
* Write "pseudocode" to plan out your analysis approach
* Translate pseudocode to functional code
* Write inline R code so you can include numbers directly in your formatted text
* Analyze relationships between two variables using a linear model
* Plot the linear relationship using an A/B line on a ggplot


# Read in data

Use the `read_excel()` function from the `readxl` package to read in the PTFE pin test data for position 0.  (Use `install.packages('readxl')` to install the package!)

> CODE CHUNK HERE

Some odd text in the output, something about new names?  Click on the data in the environment!  what's up with the column names?  

The file does not have column names right at the top; there's some extra information.  Let's assume we don't need that for now, and just skip those lines!  Check the documentation for `read_excel()` using `?read_excel`.  Note also the punctuation and spaces in the column names - hard to work with!

> CODE CHUNK HERE

# Explore the data

In the console, explore the data: use `summary()`, `head()`, `tail()`.  Write some notes about what you observe.

Try an exploratory plot - if you just pass the whole dataframe into `plot()`, you get a plot of every variable against every other variable, quick way to see if there are any obvious relationships!  Note, `plot()` is not related to `ggplot` - it is good for quick-and-dirty plots, but `ggplot` is better for nice-looking, final-report-ready plots.

> CODE CHUNK HERE


## Some potentially interesting relationships

We can plot one variable against one other easily, using `plot()`:

> CODE CHUNK HERE


What does this tell us about the dynamics of the system?

Try plotting a couple of other variable combinations, and write down some notes about what you observe.

> CODE CHUNK HERE


# Find the coefficient of kinetic friction

Kinetic friction coefficient is the ratio of the friction force to the normal force, while an object is sliding on the surface.  Static friction is when the object is not sliding.  There's already a column for the friction coefficient, but if there weren't, how could we calculate it?

## Pseudocode:

* Find just the observations where the object is sliding, velocity not zero.
* Divide the friction by the normal force.
* Take the average.

NOTE: How to deal with positive and negative values?  what if we didn't ?

> CODE CHUNK HERE


Based on this calculation, the coefficient of kinetic friction is `r mu_avg_df$mu_k_avg`.

# Find the coefficient of kinetic friction a different way

Not sure why, but it looks like the friction coefficient might be different going forward and backward... This time, let's create a statistical linear model to test the relationship.  Let's focus on observations where the velocity is at its positive constant speed of about 50 mm/s.

> CODE CHUNK HERE


## Let's explain those stats!

* Intercept: if normal force is zero, how much friction would there be? (this doesn't make much sense in this context - important to remember that a linear model might not work well, far outside the range of our data)
* fn_n: for each unit increase in this variable (normal force), the outcome variable (ff_n, friction force) would increase by this much.  
    * This is the slope of the line, delta(ff_n) / delta(fn_n), which we can interpret as the coefficient of friction!
* the p value is very very low; the usual test for statistical significance is a p-value of 0.05 or lower.
    * Null hypothesis: there is no relationship between the two variables.
    * Alt hypothesis: there is a relationship.
    * p-value: If the null hypothesis were actually true (and there were no relationship), this is the chance that we'd see a pattern like this from a random sample - very very unlikely!
    * So, we reject the null hypothesis and claim that there is a statistically significant relationship, with p < 0.05 (or p < 0.001 even).
* The R^2 value tells us how much of the observed variation is explained by our model - in this case, nearly 100% of the variation.

## Let's create a nice output plot!

This means going back to ggplot.

We need our slope and intercept information!  We can get the coefficients out of the model using the `coef()` function.  Note that this returns a named vector, and we can access those values by name, or by position (element 1 or 2).

> CODE CHUNK HERE


Based on this linear model, the coefficient of kinetic friction is `r mu_model_coef['fn_n']`.

After creating the plot, how can we make it look more professional or interesting?  Everyone think of three specific changes we could try to make, then let's figure out how to make those changes!

### some options:

* Map the color to one of the variables
* Change the axis titles
* Add a theme
* Change the color of the grid lines or panel
* Change the text font and face
